/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabi Curiel
 */
public class ViewBD extends javax.swing.JFrame {

    /**
     * Creates new form ViewE
     */
    public ViewBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jl_nombre = new javax.swing.JLabel();
        Jtf_nombre = new javax.swing.JTextField();
        jl_email = new javax.swing.JLabel();
        Jtf_email = new javax.swing.JTextField();
        Jb_guardar = new javax.swing.JButton();
        Jb_nuevo = new javax.swing.JButton();
        Jb_primero = new javax.swing.JButton();
        Jb_anterior = new javax.swing.JButton();
        Jb_siguiente = new javax.swing.JButton();
        Jb_ultimo = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jl_nombre.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jl_nombre.setText("Nombre:");

        jl_email.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jl_email.setText("Email:");

        Jb_guardar.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jb_guardar.setText("Guardar");
        Jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb_guardarActionPerformed(evt);
            }
        });

        Jb_nuevo.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jb_nuevo.setText("Nuevo");

        Jb_primero.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        Jb_primero.setText("|<");

        Jb_anterior.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        Jb_anterior.setText("<<");

        Jb_siguiente.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        Jb_siguiente.setText(">>");

        Jb_ultimo.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        Jb_ultimo.setText(">|");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jl_nombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jl_email)
                            .addGap(18, 18, 18)
                            .addComponent(Jtf_email)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jb_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(Jb_nuevo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jb_primero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jb_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jb_siguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jb_ultimo)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(Jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_email)
                    .addComponent(Jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jb_guardar)
                    .addComponent(Jb_nuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jb_primero)
                    .addComponent(Jb_anterior)
                    .addComponent(Jb_siguiente)
                    .addComponent(Jb_ultimo))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jb_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Jb_anterior;
    public javax.swing.JButton Jb_guardar;
    public javax.swing.JButton Jb_nuevo;
    public javax.swing.JButton Jb_primero;
    public javax.swing.JButton Jb_siguiente;
    public javax.swing.JButton Jb_ultimo;
    public javax.swing.JTextField Jtf_email;
    public javax.swing.JTextField Jtf_nombre;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jl_email;
    public javax.swing.JLabel jl_nombre;
    // End of variables declaration//GEN-END:variables
}
